title: FIE Referee Exam Practice
description: Practice questions for the FIE fencing referee exam.
author: Christopher Cortez

baseurl: "/FIE-Exam-Prep"
url: ""

markdown: kramdown

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - docs/*.docx
